layout_spectrum: 0.4442129865995064
typography_spectrum: 0.003026184282440803
color:
  brandStrength: 0.8873384717521765
  lightness: 0.27765476040173287
  saturation: 0.83507405693735
  rhythmicContrast: 0.7835964104134848
  brandColors:
    - '#000000'
    - '#404040'
    - '#808080'
    - '#BFBFBF'
    - '#FFFFFF'
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
name: Damien Doyle Photography
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/50bfead9-d8a9-4feb-a102-3da830cda45e.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/50bfead9-d8a9-4feb-a102-3da830cda45e.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
url: 'https://damiendoylephotography.com'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/c3f2ed89-4ee5-44c9-9d19-50cbb3d9d000.png
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/ddba9512-65b6-45ee-8848-a3792b07c0a1.png
title: Damien Doyle Photography
description: ''
github: true
