typography_spectrum: 0.13345790308743422
content_rating:
  adult: false
color:
  lightness: 0.19843619393867137
  brandColors:
    - '#000000'
    - '#000000'
    - '#000000'
    - '#000000'
    - '#000000'
  saturation: 0.8344172939470978
  brandStrength: 0.8832892590734444
  rhythmicContrast: 0.8093708669324176
github: true
opengraph: {}
layout_spectrum: 0.23921580547669738
analytics: {}
author:
  name: Damien
  url: 'http://damiendoylephotography.com'
  email: info@damiendoylephotography.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/c3f2ed89-4ee5-44c9-9d19-50cbb3d9d000.png
name: Photography Services
url: 'https://damiendoylephotography.com'
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
navigation:
  - name: Landscape
    id: 85b38c2b-3004-490e-9967-8b64804fe49c
    type: content
  - name: Aerial
    id: ddffd04a-ec21-4977-b873-7c1b1a19d74c
    type: content
  - name: Events
    id: f1c04f68-7814-4cfb-b0ba-6770adac65a8
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/ddba9512-65b6-45ee-8848-a3792b07c0a1.png
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Damien Doyle Photography
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/50bfead9-d8a9-4feb-a102-3da830cda45e.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/50bfead9-d8a9-4feb-a102-3da830cda45e.jpg
    metadata:
      datePublished: null
      keywords: []
      related: []
      author: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      app_links: []
      publisher:
        favicon: null
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: Capture the Moment
purpose:
  - type: contact
    url: 'tel:018379787'
    label: Call 018379787
  - type: contact
    url: 'mailto:info@damiendoylephotography.com'
    label: Email Me
